apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: remote
  values:
    istiodRemote:
      injectionPath: /inject/cluster/jumpingcat/net/peered
    global:
      remotePilotAddress: DISCOVERY_ADDRESS
